### PR TITLE
fix hardware architecture to generic x86-64 sse2

### PR DESCRIPTION
**Pull request by freyso**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by freyso** [comment]
@conda-forge-admin: please rerender

**Comment by jan-janssen** [comment]
Is this in conflict with:
```
 +CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/sphinxdft-3.0.3 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
```
typically `march` is defined via the `CFLAGS`, `FFLAGS` and so on.

**Comment by freyso** [comment]
no. the SPHInX build environment ignores external CXXFLAGS, because they proved complete rubbish for HPC tasks. We set our own flags. CXX_MARCH is our own variable to control architecture independent of the other settings that may depend on the configure options. If not given, it is set to -march=native, which pins the hardware to the machine the code is compiled on. Good for real HPC systems, bad for crappy builds that must run everywhere, like the condaforge build.

**Comment by jan-janssen** [comment]
Ok, can we then just use `-march=nocona -mtune=haswell` to be consistent with conda?

**Comment by freyso** [comment]
x86-64 is slightly more generic than nocona, but the extensions that come with nocona are useless for SPHInX. Tuning for haswell is unlikely to result in performance improvements, as you leave out the major modern CPU features responsible for performance anyway.
I am not sure how often condaforge changes their architectural defaults; x86-64 to me seems the better choice. But I won't insist.

**Comment by jan-janssen** [comment]
Ok, I am happy to give it a try.

**Pull request merged**
